name: log450_doit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  fluttertoast: ^8.2.4
  http: ^1.2.0
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/doit.webp
     - assets/createaccounticon.png
     - assets/loginicon.png
     - assets/LoaderTask.json
     - assets/partyimage.jpg
     - assets/paddleboard.jpg
     - assets/amusementpark.jpg
     - assets/meeting.jpg
     - assets/male1.png
     - assets/male2.png
     - assets/female1.png
     - assets/female2.png
     - assets/Logo.png
