name: log450_doit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  fluttertoast: ^8.2.4
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.17.0

flutter:
  uses-material-design: true
  assets:
     - assets/doit.webp
     - assets/createaccounticon.png
     - assets/loginicon.png
     - assets/LoaderTask.json
     - assets/partyimage.jpg
     - assets/paddleboard.jpg
     - assets/amusementpark.jpg
     - assets/meeting.jpg
     - assets/male1.png
     - assets/male2.png
     - assets/female1.png
     - assets/female2.png
